# Generated by Django 5.2 on 2025-08-14 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duracao', models.DurationField(verbose_name='duração estimada')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicos', to='agendamento.categoria')),
                ('profissional', models.ForeignKey(limit_choices_to={'user_type': 'PROFISSIONAL'}, on_delete=django.db.models.deletion.CASCADE, related_name='servicos_oferecidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_inicio', models.DateTimeField(verbose_name='início do agendamento')),
                ('data_hora_fim', models.DateTimeField(blank=True, verbose_name='fim do agendamento')),
                ('status', models.CharField(choices=[('AGENDADO', 'Agendado'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='AGENDADO', max_length=10)),
                ('cliente', models.ForeignKey(limit_choices_to={'user_type': 'CLIENTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_feitos', to=settings.AUTH_USER_MODEL)),
                ('profissional', models.ForeignKey(limit_choices_to={'user_type': 'PROFISSIONAL'}, on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_recebidos', to=settings.AUTH_USER_MODEL)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agendamento.servico')),
            ],
        ),
    ]
