# Generated by Django 5.2 on 2025-08-19 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='profissional',
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='data_hora_fim',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='fim do agendamento'),
        ),
    ]
