# Generated by Django 5.2 on 2025-08-19 19:57

from django.db import migrations

# SQL para a conversão de 'interval' para 'integer' (minutos)
# Pega o total de segundos do intervalo (EPOCH), divide por 60 e converte para inteiro.
sql_forward = """
ALTER TABLE "agendamento_servico"
ALTER COLUMN "duracao" TYPE integer
USING (EXTRACT(EPOCH FROM duracao) / 60)::integer;
"""

# SQL para reverter a operação, de 'integer' (minutos) para 'interval'
# Cria um intervalo a partir do total de segundos (minutos * 60).
sql_backward = """
ALTER TABLE "agendamento_servico"
ALTER COLUMN "duracao" TYPE interval
USING make_interval(secs => duracao * 60);
"""


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0002_remove_agendamento_profissional_and_more'),
    ]

    operations = [
        # Substituímos a operação AlterField padrão por uma operação RunSQL
        # que lida com a conversão de dados no PostgreSQL.
        migrations.RunSQL(sql_forward, reverse_sql=sql_backward),
    ]
