# Generated by Django 5.2 on 2025-08-19 17:15

from django.db import migrations

# SQL para converter de integer (minutos) para interval
sql_forward = """
ALTER TABLE "agendamento_servico"
ALTER COLUMN "duracao" TYPE interval
USING make_interval(secs => duracao * 60);
"""

# SQL para reverter, de interval para integer (minutos)
sql_backward = """
ALTER TABLE "agendamento_servico"
ALTER COLUMN "duracao" TYPE integer
USING (EXTRACT(EPOCH FROM duracao) / 60)::integer;
"""

class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0003_alter_servico_duracao'),
    ]

    operations = [
        migrations.RunSQL(sql_forward, reverse_sql=sql_backward),
    ]